### PR TITLE
Check if end date is being set to a pending task

### LINKED ISSUE #3584: Modifying the end property silently fails
```
$ task add smile
Created task 1.

$ task
ID Age  Description Urg
 1 1s   smile          0

$ task 1 mod end:-7d
Modifying task 1 'smile'.
Modified 1 task.

$ task
ID Age   Description Urg
 1 18s   smile          0
```

I expected that modifying the end property will succeed. Or, alternatively, that it will fail with some explanation and non-zero exit code.

I observed this behavior in both 2.6.2 and 3.0.2.

### PR DESCRIPTION
**Pull request by gagankonana**
Fixes #3584 
- throw error if end date is being set to a pending task
- add a test for the bug

### CODE REVIEW

File: src/commands/CmdModify.cpp [hunk 1]
```diff
@@ -116,6 +116,11 @@ void CmdModify::checkConsistency(Task &before, Task &after) {
 
   if (before.has("recur") && (!after.has("recur") || after.get("recur") == ""))
     throw std::string("You cannot remove the recurrence from a recurring task.");
+
+  if ((before.getStatus() == Task::pending) && (after.getStatus() == Task::pending) &&
+      (after.get("end") != ""))
+    throw format("Could not modify task {1}. You cannot set an end date on a pending task.",
+                 before.identifier(true));
```
Comment (djmitche) [inline src/commands/CmdModify.cpp:123]: To answer your [question from the issue](https://github.com/GothenburgBitFactory/taskwarrior/issues/3584#issuecomment-2347969857), in this context I would prefer a warning since tasks might be `pending` but have an `end` from some other cause, and this will cause Taskwarrior to return an error even when the rnuning `task` command did not modify either of these properties.

That said, as you have seen there are lots of other `throw`s in this function, and I think adding another is the right course. We can think about converting them to warnings later.

**Review by djmitche — APPROVED** [review]

File: src/commands/CmdModify.cpp (hunk 1 above)
Comment (djmitche) [reply src/commands/CmdModify.cpp:123]: Oh, sorry, I admit I copy-pasted this comment from the other PR and didn't notice it's now in `CmdModify`! I think this is a much better fix :)

**Review by djmitche — APPROVED** [review]

**Comment by gagankonana** [comment]
@djmitche awesome! Do you know why PR failed one of the checks - tests (Ubuntu 20.04, ubuntu-latest, ubuntu2004)? I am just curious.

**Comment by djmitche** [comment]
I peeked at that failure, and saw some errors in installing Ubuntu packages that the job depended on, so I assume something was wrong there, unrelated to your changes. If I see that failure in another PR, I'll look into what's going on.

**Comment by gagankonana** [comment]
Got it. Thanks for checking!
