### PR TITLE
Check Datetime addition when performing recurrence

### LINKED ISSUE #81: [TW-19] no maximum recur leads to an infinite loop in gc from overflow of int
_Scott Kostyshak on 2012-09-01T23:17:31Z says:_ 

 To reproduce:

1. task add brush my teeth recur:70years due:today
2. task

(2) puts me into an infinite loop in generateDueDates.

### PR DESCRIPTION
**Pull request by djmitche**
If the Datetime arithmetic overflows, this just stops recurrence entirely. This means that `recur:70y` will basically not recur. And, it means that a repeated recurrence of a more reasonable period (say, `recur:2d`) will stop in 2038 on 32-bit systems.

Fixes #81.

### CODE REVIEW

File: src/recur.cpp [hunk 1]
```diff
@@ -47,8 +47,28 @@
...
 #include <iomanip>
 #include <iostream>
+#include <limits>
+#include <optional>
 #include <sstream>
 
+namespace {
+
+// Add a `time_t` delta to a Datetime, checking for and returning nullopt on integer overflow.
+std::optional<Datetime> checked_add(Datetime& base, time_t delta) {
```
Comment (Necior) [inline src/recur.cpp]: As a pure function, it is is a good candidate for a unit test.

File: src/recur.cpp [hunk 2]
```diff
@@ -47,8 +47,28 @@
...
+  // Datetime::operator+ takes an integer delta, so chek that range
```
Comment (Necior) [inline src/recur.cpp]: s/chek/check/

**Review by Necior — APPROVED** [review]

File: src/recur.cpp (hunk 1 above)
Comment (djmitche) [reply src/recur.cpp]: I wish there was a way to test private functions. I'll just make this one public to test it.

**Review by Necior — APPROVED** [review]
