### PR TITLE
Check that sync.server.origin is a URL

### LINKED ISSUE #3349: task 3.0.0 and taskchampion-sync-server on localhost/oracle fails to sync
#### To report a bug...

I've built task 3.0.0 and taskchampion-sync-server from release tarball. I've opened 8443 port on my localhost and oracle machine (I was testing both options). I've set taskrc:
```
sync.server.origin=localhost:8443
sync.server.client_id=4b21ecf6-520b-4b16-b265-4853b400f4ed
sync.encryption_secret=blabla
```
and built and run taskchampion-sync-server (with and w/o release flag - the result was the same):
```
cargo build -p taskchampion-sync-server --release
./target/release/taskchampion-sync-server --port 8443 --data-dir ./data
```
When I run `task sync` I get this error `Failed to synchronize with server`

Output from task diag:
```
task 3.0.0
   Platform: Linux

Compiler
    Version: 9.4.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      CMake: 3.29.1
    libuuid: libuuid + uuid_unparse_lower
 Build type: release

Configuration
       File: /home/marek/.taskrc (found), 1551 bytes, mode 100664
       Data: /home/marek/.task (found), dir, mode 40775
    Locking: Enabled
         GC: Enabled
Hooks
     System: Enabled
   Location: /home/marek/.task/hooks
             (-none-)

Tests
   Terminal: 120x30
       Dups: Scanned 0 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 0 tasks for broken references:
             No broken references found
```

What am I doing wrong? I've searched other issues related to taskwarrior 3.0 and taskchampion-sync-server and couldn't find solution.

### PR DESCRIPTION
**Pull request by djmitche**
Note that due to #3326 this still appears as "Unknown error. Please report." but at least it is reported now.

### CODE REVIEW

File: taskchampion/taskchampion/src/server/sync/mod.rs [hunk 1]
```diff
@@ -28,8 +29,16 @@ impl SyncServer {
     /// identify this client to the server.  Multiple replicas synchronizing the same task history
     /// should use the same client_id.
     pub fn new(origin: String, client_id: Uuid, encryption_secret: Vec<u8>) -> Result<SyncServer> {
+        let origin = Url::parse(&origin)
+            .map_err(|_| Error::Server(format!("Could not parse {} as a URL", origin)))?;
+        if origin.path() != "/" {
+            return Err(Error::Server(format!(
+                "Server origin must have an empty path; got {}",
+                origin
+            )));
```
Comment (ryneeverett) [inline taskchampion/taskchampion/src/server/sync/mod.rs:38]: Why does the origin require an empty path? I hope this is sufficiently documented in taskchampion-sync-server so people don't set it up on a subdirectory before running into this error.

**Review by ryneeverett — APPROVED** [review]

File: taskchampion/taskchampion/src/server/sync/mod.rs (hunk 1 above)
Comment (djmitche) [reply taskchampion/taskchampion/src/server/sync/mod.rs:38]: An [origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin) is the scheme/hostname/port, so I think with the current naming of the config a path is prohibited. I'll file a new bug to rename to url and allow a path (with trivial backward compatibility)
